services:
  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_DB: trello_clone_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#  app:
#    build: .
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trello_clone_db
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: password1234
#      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
#
volumes:
  db_data: